<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga [
    <!ELEMENT liga (jugador+)>
        
        <!ELEMENT jugador (nombre, apellidos, equipo, edad)>
            
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT apellidos (#PCDATA)>
            
            <!ELEMENT equipo (ciudad, presidente)>
            
                <!ELEMENT ciudad (#PCDATA)>
                
                <!ELEMENT presidente (nombrePresidente, apellidosPresidente)>
                
                    <!ELEMENT nombrePresidente (#PCDATA)>
                    <!ELEMENT apellidosPresidente (#PCDATA)>
            
            <!ELEMENT edad (#PCDATA)>
]>


<!-- 
Nombre: Henry Leonardo Talavera Velasquez 
Curso: DAW1
Fecha: 2/4/2025 
Ejercicio: Ejercicio 2
-->

<liga>
    <!-- Primer Jugador -->
    <jugador>
        <nombre>LeBron</nombre>
        <apellidos>James</apellidos>
        <equipo>
            <ciudad>Los Angeles</ciudad>
            <!-- Datos del Presidente de Equipo -->
            <presidente>
                <nombrePresidente>Jeanie</nombrePresidente>
                <apellidosPresidente>Buss</apellidosPresidente>
            </presidente>
        </equipo>
        <edad>39</edad>
    </jugador>

    <!-- Segundo Jugador -->
    <jugador>
        <nombre>Stephen</nombre>
        <apellidos>Curry</apellidos>
        <equipo>
            <ciudad>San Francisco</ciudad>
            <!-- Datos del Presidente de Equipo -->
            <presidente>
                <nombrePresidente>Joe</nombrePresidente>
                <apellidosPresidente>Lacob</apellidosPresidente>
            </presidente>
        </equipo>
        <edad>36</edad>
    </jugador>

    <!-- Tercer Jugador -->
    <jugador>
        <nombre>Luka</nombre>
        <apellidos>Dončić</apellidos>
        <equipo>
            <ciudad>Dallas</ciudad>
            <!-- Datos del Presidente de Equipo -->
            <presidente>
                <nombrePresidente>Nico</nombrePresidente>
                <apellidosPresidente>Harrison</apellidosPresidente>
            </presidente>
        </equipo>
        <edad>25</edad>
    </jugador>
</liga>

